//! Link model types shared across the `core` and `markdown` crates.
//!
//! Architecture:
//!
//! - `LinkIndex` is populated by the markdown renderer during a `render_terminal_with_links` call and stored on App.
//! - It is rebuilt on every matching `RenderResult` arrival in `App::tick()` so it always reflects the current document content.
//!
//! Link target classification:
//!
//! | URL shape                      | `LinkTarget` variant |
//! |--------------------------------|----------------------|
//! | `http://...` or `https://...`  | `External`           |
//! | starts with `#`                | `InternalAnchor`     |
//! | `[[page]]` or `[[page|title]]` | `WikiLink`           |
//! | anything else                  | `FilePath`           |
//!
//! Anchor normalization:
//!
//! GitHub-compatible heading anchor IDs are generated by `normalize_anchor` (lowercase, strip all chars except letters/digits/spaces/hyphens, replace spaces with hyphens).

use std::path::PathBuf;

// --------------------------------------------------------------
// LinkTarget
// --------------------------------------------------------------

/// The destination a link points to.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LinkTarget {
    /// An external URL that should be opened in the system browser.
    External(String),

    /// An in-document anchor (e.g. '#heading-id'). The stored value is the normalized ID without the leading '#'.
    InternalAnchor(String),

    /// A `[[wiki-link]]` or `[[wiki-link|title]]`.
    /// Cross-file navigation is not supported in MVP. Following one simply shows a notification for now.
    WikiLink(String),

    /// A relative or absolute file path (e.g. `./notes.md`).
    /// NOTE: Navigation deferred to post-MVP.
    FilePath(PathBuf),
}

impl LinkTarget {
    /// Classify a raw URL/href string into the appropriate LinkTarget variant.
    pub fn from_href(href: &str) -> Self {
        let trimmed = href.trim();
        if trimmed.starts_with("http://") || trimmed.starts_with("https://") {
            Self::External(trimmed.to_owned())
        } else if let Some(anchor) = trimmed.strip_prefix('#') {
            Self::InternalAnchor(anchor.to_owned())
        } else {
            // Could be a file path or an anchor without '#'.
            // NOTE: Treat as FilePath for now.
            Self::FilePath(PathBuf::from(trimmed))
        }
    }

    /// A short human-readable label for display in the LinkSelect prompt.
    pub fn display_str(&self) -> &str {
        match self {
            Self::External(u) => u.as_str(),
            Self::InternalAnchor(a) => a.as_str(),
            Self::WikiLink(w) => w.as_str(),
            Self::FilePath(p) => p.to_str().unwrap_or("(invalid path)"),
        }
    }
}

// --------------------------------------------------------------
// Link
// --------------------------------------------------------------

/// A single link extracted from the document.
#[derive(Debug, Clone)]
pub struct Link {
    /// The visible text shown for the link (e.g. "Click here").
    /// May be empty for bare-URL links.
    pub display_text: String,

    /// Where the link points.
    pub target: LinkTarget,

    /// 0-indexed line number in the document source where the link opens.
    /// Used to jump the editor cursor to the link source on `FollowLink`.
    pub source_line: usize,

    /// 0-indexed char column within `source_line` where the link opens.
    pub source_col: usize,
}

// --------------------------------------------------------------
// LinkIndex
// --------------------------------------------------------------

/// An ordered list of all links extracted during a single render pass.
///
/// App owns one instance that's replaced wholesale on every successful `RenderResult`.
/// The ordering matches document order (links appear in the order the renderer visits them).
#[derive(Debug, Clone, Default)]
pub struct LinkIndex(pub Vec<Link>);

impl LinkIndex {
    /// Construct an empty index.
    pub fn new() -> Self {
        Self(Vec::new())
    }

    /// Push a link onto the index.
    pub fn push(&mut self, link: Link) {
        self.0.push(link);
    }

    /// `true` when the index contains no links.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// Total number of links in the index.
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Return the link at `index` if one exists.
    pub fn get(&self, index: usize) -> Option<&Link> {
        self.0.get(index)
    }
}

// --------------------------------------------------------------
// Anchor normalization
// --------------------------------------------------------------

/// Convert heading text to a GitHub-compatible anchor ID.
///
/// Rules:
/// 1. Lowercase everything.
/// 2. Strip all characters except ASCII letters, digits, spaces, and hyphens.
/// 3. Replace spaces with hyphens.
///
/// Example: "My Heading (2024)" -> "my-heading-2024"
pub fn normalize_anchor(heading_text: &str) -> String {
    heading_text
        .to_lowercase()
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == ' ' || *c == '-')
        .collect::<String>()
        .split_whitespace()
        .collect::<Vec<_>>()
        .join("-")
}

// --------------------------------------------------------------
// Tests
// --------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // LinkTarget::from_href

    #[test]
    fn https_url_is_external() {
        let t = LinkTarget::from_href("https://example.com/path?q=1");

        assert!(matches!(t, LinkTarget::External(_)));
    }

    #[test]
    fn http_url_is_external() {
        let t = LinkTarget::from_href("http://example.com");

        assert!(matches!(t, LinkTarget::External(_)));
    }

    #[test]
    fn hash_prefix_is_internal_anchor() {
        let t = LinkTarget::from_href("#my-heading");

        assert!(matches!(t, LinkTarget::InternalAnchor(a) if a == "my-heading"));
    }

    #[test]
    fn relative_path_is_file_path() {
        let t = LinkTarget::from_href("./notes.md");

        assert!(matches!(t, LinkTarget::FilePath(_)));
    }

    #[test]
    fn bare_path_is_file_path() {
        let t = LinkTarget::from_href("docs/overview.md");

        assert!(matches!(t, LinkTarget::FilePath(_)));
    }

    // normalize_anchor

    #[test]
    fn lowercase_and_hyphenate() {
        assert_eq!(normalize_anchor("My Heading"), "my-heading");
    }

    #[test]
    fn strips_punctuation_except_hyphens() {
        assert_eq!(normalize_anchor("Hello, World! (2024)"), "hello-world-2024");
    }

    #[test]
    fn existing_hyphens_preserved() {
        assert_eq!(normalize_anchor("pre-existing"), "pre-existing");
    }

    #[test]
    fn multiple_spaces_become_single_hyphen() {
        assert_eq!(normalize_anchor("a   b"), "a-b");
    }

    #[test]
    fn empty_string_produces_empty_anchor() {
        assert_eq!(normalize_anchor(""), "");
    }

    // LinkIndex

    #[test]
    fn new_index_is_empty() {
        let idx = LinkIndex::new();

        assert!(idx.is_empty());
        assert_eq!(idx.len(), 0);
    }

    #[test]
    fn push_and_len() {
        let mut idx = LinkIndex::new();
        idx.push(Link {
            display_text: "Example".into(),
            target: LinkTarget::External("https://example.com".into()),
            source_line: 0,
            source_col: 0,
        });

        assert_eq!(idx.len(), 1);
        assert!(!idx.is_empty());
    }

    #[test]
    fn get_returns_correct_link() {
        let mut idx = LinkIndex::new();
        idx.push(Link {
            display_text: "One".into(),
            target: LinkTarget::External("https://one.com".into()),
            source_line: 0,
            source_col: 0,
        });
        idx.push(Link {
            display_text: "Two".into(),
            target: LinkTarget::External("https://two.com".into()),
            source_line: 1,
            source_col: 0,
        });

        assert_eq!(idx.get(1).unwrap().display_text, "Two");
        assert!(idx.get(2).is_none());
    }

    // display_str

    #[test]
    fn external_display_str_is_url() {
        let t = LinkTarget::External("https://example.com".into());

        assert_eq!(t.display_str(), "https://example.com");
    }

    #[test]
    fn internal_anchor_display_str_is_anchor_id() {
        let t = LinkTarget::InternalAnchor("my-section".into());

        assert_eq!(t.display_str(), "my-section");
    }

    #[test]
    fn wiki_link_display_str_is_page_name() {
        let t = LinkTarget::WikiLink("HomePage".into());

        assert_eq!(t.display_str(), "HomePage");
    }
}
